apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: co2-app
  name: co2-app
spec:
  ports:
    - name: 8080-8080
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: co2-app
  type: LoadBalancer
status:
  loadBalancer: {}
